query GetUserAndTopProduct {
  me {
    id
    username
  }
  topProducts(first: 1) {
    upc
    name
    price
    reviews {
      body
      author {
        id
        username
      }
    }
  }
}
